---
- name: installing systemd units...
  become: yes
  become_user: root
  register: couchdb_backup_modified
  with_items:
    - {f: usr/lib/systemd/system/couchdb-backup.timer, m: '0644' }
    - {f: usr/lib/systemd/system/couchdb-backup.service, m: '0644'}
    - {f: usr/local/bin/couchdb-backup.sh, m: '0755'}
  template: >-
    src={{item.f}}.j2
    dest=/{{item.f}}
    mode={{item.m}}
    
- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: couchdb_backup_modified|changed
  command: systemctl daemon-reload

- name: launch timer
  become: yes
  become_user: root
  service: name=couchdb-backup.timer enabled=true state=started
